
  export const users =[
    {
      id:"1",
      username:"salama",
      email:"salama@salama.com",
      transaction:121.0,
      img:"/img/nature.jpg",
      status:"pending",
      job:"software engineer",
      phone:"0102584952",
      brithday:"12/12/2012",
      city:"new york",
      country:"usa",
      fullname:"salama naief"
    },
    {
      id:"2",
      username:"ebrahim",
      email:"ebrahim@salama.com",
      transaction:100.0,
      img:"/img/nature.jpg",
      status:"pending",
      job:"software engineer",
      phone:"0102584952",
      brithday:"12/12/2012",
      city:"new york",
      country:"usa",
      fullname:"ebrahim naief"
    },
    {
      id:"3",
      username:"hussan",
      email:"hussan@salama.com",
      transaction:210.0,
      img:"/img/nature.jpg",
      status:"pending",
      job:"software engineer",
      phone:"0102584952",
      brithday:"12/12/2012",
      city:"new york",
      country:"usa",
      fullname:"hussan naief"
    },
    {
      id:"4",
      username:"hassan",
      email:"hassan@salama.com",
      transaction:130.0,
      img:"/img/nature.jpg",
      status:"pending",
      job:"software engineer",
      phone:"0102584952",
      brithday:"12/12/2012",
      city:"new york",
      country:"usa",
      fullname:"hassan naief"
    },
    {
      id:"5",
      username:"ahmed",
      email:"ahmed@salama.com",
      transaction:170.0,
      img:"/img/nature.jpg",
      status:"pending",
      job:"software engineer",
      phone:"0102584952",
      brithday:"12/12/2012",
      city:"new york",
      country:"usa",
      fullname:"ahmed naief"
    },
    {
      id:"6",
      username:"mohamed",
      email:"mohamed@salama.com",
      transaction:155.0,
      img:"/img/nature.jpg",
      status:"pending",
      job:"software engineer",
      phone:"0102584952",
      brithday:"12/12/2012",
      city:"new york",
      country:"usa",
      fullname:"mohamed naief"
    },
  ]

  export const productData =[
    {
      id:"1",
      name:"iPhone",
      price:"125",
      status:"active",
      stock:"120",
      tag:"phones",
      offers:"100",
      date:"12/1/2015",
      img:"hero.jpg",
      rating:"4.6"
    },
    {
      id:"2",
      name:"lenovo",
      price:"80",
      status:"active",
      stock:"120",
      tag:"phones",
      offers:"100",
      date:"12/1/2015",
      img:"hero.jpg",
      rating:"4.3"
    },
    {
      id:"3",
      name:"redmi",
      price:"100",
      status:"active",
      stock:"120",
      tag:"phones",
      offers:"100",
      date:"12/1/2015",
      img:"nature.jpg",
      rating:"4.4"
    },
     {
      id:"4",
      name:"samsung",
      price:"125",
      status:"active",
      stock:"120",
      tag:"phones",
      offers:"100",
      date:"12/1/2015",
      img:"hero.jpg",
      rating:"4.4"
    },
    {
     id:"5",
     name:"iPhone",
     price:"125",
     status:"active",
     stock:"120",
     tag:"phones",
     offers:"100",
     date:"12/1/2015",
     img:"nature.jpg",
      rating:"4.1"
   },
   {
    id:"6",
    name:"hawawi",
    price:"109",
    status:"active",
    stock:"120",
    tag:"phones",
    offers:"99",
    date:"12/1/2015",
    img:"hero.jpg",
      rating:"4.5"
  }
  ]